# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

# to override
prepend_keymap = [
	# Seeking
	{ on = "<A-k>", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "<A-j>", run = "seek 5",  desc = "Seek down 5 units in the preview" },

	{ on = [ "\\", "s" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
	{ on = [ "\\", "d" ], run = ''' shell 'ripdrag --and-exit --no-click "$@" 2>/dev/null &' --confirm ''', desc = "Drap on Drop exit 1th" },
	{ on = [ "\\", "D" ], run = ''' shell 'ripdrag --no-click "$@" 2>/dev/null &' --confirm ''', desc = "Drap on Drop no-exit" },
	{ on = [ "\\", "s" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
	{ on = [ "\\", "t" ], run = "plugin hide-preview", desc = "Toggle preview pane" },
	{ on = [ "\\", "T" ], run = "plugin max-preview", desc = "Maximize or restore preview" },

	{ on = "F", run = "plugin smart-filter", desc = "Smart filter" },
	{ on = "K", run = "plugin parent-arrow --args=-1" },
	{ on = "J", run = "plugin parent-arrow --args=1" },
	{ on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

	# { on = "n", run = "plugin relative-motions", desc = "Trigger a new relative motion" },
	{ on = "1", run = "plugin relative-motions 1", desc = "Move in relative steps" },
	{ on = "2", run = "plugin relative-motions 2", desc = "Move in relative steps" },
	{ on = "3", run = "plugin relative-motions 3", desc = "Move in relative steps" },
	{ on = "4", run = "plugin relative-motions 4", desc = "Move in relative steps" },
	{ on = "5", run = "plugin relative-motions 5", desc = "Move in relative steps" },
	{ on = "6", run = "plugin relative-motions 6", desc = "Move in relative steps" },
	{ on = "7", run = "plugin relative-motions 7", desc = "Move in relative steps" },
	{ on = "8", run = "plugin relative-motions 8", desc = "Move in relative steps" },
	{ on = "9", run = "plugin relative-motions 9", desc = "Move in relative steps" },

	{ on = [ "m", "b" ], run = "plugin bookmarks --args=save", desc = "Save current position as a bookmark" },
	{ on = "'", run = "plugin bookmarks --args=jump", desc = "Jump to a bookmark" },
	{ on = [ "b", "d" ], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark" },
	{ on = [ "b", "D" ], run = "plugin bookmarks --args=delete_all", desc = "Delete all bookmarks" },
]

append_keymap = [
	# Goto
	{ on = [ "g", "d" ],       run = "cd ~/Downloads/", desc = "Go to ~/Downloads" },
	{ on = [ "g", "f" ],       run = "cd /disks/Vault/Financeiro/", desc = "Go to Financeiro directory" },
	{ on = [ "g", "t" ],       run = "cd /tmp/", desc = "Go to /tmp" },
]
