# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

[flavor]
# dark = "kanagawa"
dark = "catppuccin-mocha"

[mgr]
border_style = { fg = "#434a57"}

# [tabs]
# active   = { fg = "#24273a", bg = "#8aadf4", bold = true }
# inactive = { fg = "#8aadf4", bg = "#363a4f" }
