background_opacity 0.7
background_blur 8

macos_option_as_alt yes

# Kitty will ignore the event to make macOS intercept it
# This is to use the native macOS Emoji Selector
map ctrl+cmd+space discard_event
# map ctrl+cmd+space no_op



